# Generated by Django 2.2.7 on 2020-08-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='prod_name')),
                ('salary', models.FloatField(verbose_name='prod_price')),
                ('age', models.IntegerField(verbose_name='prod_qty')),
                ('desig', models.CharField(max_length=20, verbose_name='prod_remarks')),
            ],
        ),
    ]
