# Generated by Django 2.2.7 on 2020-08-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('salary', models.FloatField(verbose_name='salary')),
                ('age', models.IntegerField(verbose_name='age')),
                ('desig', models.CharField(max_length=20, verbose_name='designation')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
